### ISSUE TITLE
小米mix2下载过程中随着进度变化手机会一直震动

### ISSUE THREAD

**Issue by aiceking** [sunfusheng/FirUpdater#1]

**Comment by AriesHoo** [comment]
我的小米6会没进度变化一次 响铃一次

**Comment by sunfusheng** [comment]
升级时不停震动不停响铃的问题解决了，是Android8.0兼容性的问题，参考的这篇文章https://blog.csdn.net/androidzmm/article/details/80679804
请使用V1.1.1
